import type { Role } from "@/api/types";
import type { TourDefinition } from "@/features/onboarding/types";

const ADMINS: Role[] = ["SCHOOL_ADMIN", "BRANCH_ADMIN"];
const STAFF: Role[] = ["SCHOOL_ADMIN", "BRANCH_ADMIN", "TEACHER"];

/**
 * Page guides for the school portal. Every guide is gated on its `navHref` being visible to the
 * caller (see TourDefinition.navHref), so a guide for a feature the school isn't entitled to, or a
 * page the role can't reach, is never offered.
 */
export const SCHOOL_TOURS: TourDefinition[] = [
  {
    key: "school.dashboard",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Your dashboard",
    description: "What the dashboard shows you each time you sign in.",
    area: "Getting started",
    roles: ["SCHOOL_ADMIN", "BRANCH_ADMIN", "TEACHER", "INVENTORY_MANAGER"],
    route: "/school",
    navHref: "/school",
    steps: [
      {
        target: "page-header",
        roles: ADMINS,
        title: "Your school at a glance",
        body: "The dashboard sums up your school: students, staff, the current term and anything that needs your attention.",
      },
      {
        target: "page-header",
        roles: ["TEACHER"],
        title: "Your day at a glance",
        body: "The dashboard shows the classes and subjects you teach, and what still needs doing this term.",
      },
      {
        target: "page-header",
        roles: ["INVENTORY_MANAGER"],
        title: "Your store at a glance",
        body: "See items that are low or out of stock, and the progress of the purchase requests you've raised.",
      },
    ],
  },
  {
    key: "school.sessions",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Sessions & terms",
    description: "Set up the academic calendar that every score and attendance mark is filed under.",
    area: "Setting up your school",
    roles: ADMINS,
    route: "/school/academics/sessions",
    navHref: "/school/academics/sessions",
    steps: [
      {
        target: "page-header",
        title: "The academic calendar",
        body: "A session (for example 2026/2027) has up to three terms. Start with the first term and add the others when their dates are known.",
      },
      {
        target: "page-actions",
        title: "Add a session",
        body: "Create a session with its first term here. You can edit the dates later.",
      },
      {
        title: "Mark the current term",
        body: "Mark one session and one term as current. Scores, attendance and teachers' lists all follow the current term. KDLMS never changes it from the date alone.",
      },
    ],
  },
  {
    key: "school.classes",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Classes",
    description: "Name and order your school's classes (stages) and organise subjects into groups.",
    area: "Setting up your school",
    roles: ["SCHOOL_ADMIN"],
    route: "/school/academics/classes",
    navHref: "/school/academics/classes",
    steps: [
      {
        target: "page-header",
        title: "Your schooling stages",
        body: "Classes are listed in promotion order, for example Nursery 1 then Primary 1. Rename or reorder them to match your school.",
      },
      {
        target: "page-actions",
        title: "Add a class",
        body: "Add another class against a stage. For example, add both Junior Secondary and Senior Secondary under Secondary.",
      },
      {
        title: "What comes next",
        body: "Once your classes are in place, add subjects and classrooms for each one, then set its grading system.",
      },
    ],
  },
  {
    key: "school.classrooms",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Classrooms",
    description: "Create classrooms per branch and assign class and subject teachers.",
    area: "Setting up your school",
    roles: STAFF,
    route: "/school/academics/classrooms",
    navHref: "/school/academics/classrooms",
    steps: [
      {
        target: "page-header",
        roles: ADMINS,
        title: "Classrooms",
        body: "A classroom is an arm of a class at a branch, for example Primary 1 Gold. Open one to assign its class teacher, an assistant and its subject teachers.",
      },
      {
        target: "page-actions",
        roles: ADMINS,
        title: "Add a classroom",
        body: "Create a classroom, choosing its class and branch.",
      },
      {
        target: "page-header",
        roles: ["TEACHER"],
        title: "Your classrooms",
        body: "These are the classrooms you class-teach or subject-teach. Open one to see its students and subjects.",
      },
    ],
  },
  {
    key: "school.subjects",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Subjects",
    description: "Build each class's subject catalogue, including selective subjects and term-only subjects.",
    area: "Setting up your school",
    roles: STAFF,
    route: "/school/academics/subjects",
    navHref: "/school/academics/subjects",
    steps: [
      {
        target: "page-header",
        roles: ADMINS,
        title: "The subject catalogue",
        body: "Each class has its own subjects, optionally sectioned into groups such as Sciences or Languages. Groups also section the printed report.",
      },
      {
        title: "Selective and termly subjects",
        roles: ADMINS,
        body: "By default every student takes every subject, all year. Mark a subject as selective to register only some students for it, or limit it to the terms it's taught in.",
      },
      {
        target: "page-header",
        roles: ["TEACHER"],
        title: "Your subjects",
        body: "These are the subjects you teach this term, by classroom.",
      },
    ],
  },
  {
    key: "school.teachers",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Teachers",
    description: "Invite teachers and see their class and subject assignments.",
    area: "People",
    roles: ADMINS,
    route: "/school/academics/teachers",
    navHref: "/school/academics/teachers",
    steps: [
      {
        target: "page-header",
        title: "Your teaching staff",
        body: "Every teacher has their own login. They only see the classes and subjects they're assigned to.",
      },
      {
        target: "page-actions",
        title: "Add a teacher",
        body: "Add a teacher with their email. They receive a temporary password and set their own when they first sign in.",
      },
      {
        title: "Heads of level",
        roles: ["SCHOOL_ADMIN"],
        body: "You can make a teacher Head of Level for one or more classes. They then get admin-level access to those classes' academics.",
      },
    ],
  },
  {
    key: "school.students",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Students",
    description: "Register students, find a student quickly and open their full record.",
    area: "People",
    roles: ["SCHOOL_ADMIN", "BRANCH_ADMIN", "TEACHER", "INVENTORY_MANAGER"],
    route: "/school/students",
    navHref: "/school/students",
    steps: [
      {
        target: "page-header",
        roles: ADMINS,
        title: "The student registry",
        body: "Every student registered at your school. Search by name or admission number, then open a student for their profile, guardians, results and subjects.",
      },
      {
        target: "page-actions",
        roles: ADMINS,
        title: "Register a student",
        body: "Register a student straight into a classroom. An admission number is generated for you.",
      },
      {
        title: "Promotion",
        roles: ADMINS,
        body: "At the end of a session, use the promotion screen (next to Register student) to move students into the next session's classes.",
      },
      {
        target: "page-header",
        roles: ["TEACHER"],
        title: "Your students",
        body: "Pick one of your classrooms to see its current roster.",
      },
      {
        target: "page-header",
        roles: ["INVENTORY_MANAGER"],
        title: "Student registry",
        body: "A read-only list of your branch's students. You'll use it when issuing items to a student.",
      },
    ],
  },
  {
    key: "school.grading",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Grading systems",
    description: "Set how each class is assessed: numeric scores and grades, or a qualitative rating scale.",
    area: "Setting up your school",
    roles: ["SCHOOL_ADMIN"],
    route: "/school/assessments/grading",
    navHref: "/school/assessments/grading",
    steps: [
      {
        target: "page-header",
        title: "One grading system per class",
        body: "Numeric classes use grade boundaries and weightings, for example 30% quiz and 70% exam. Early-years classes use a rating scale with observations instead.",
      },
      {
        title: "Set it before scores go in",
        body: "You can switch a class between numeric and qualitative only until its first score or rating is recorded.",
      },
    ],
  },
  {
    key: "school.assessments",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Recording scores",
    description: "Enter quiz and exam scores, or ratings, and review a class's results.",
    area: "Teaching",
    roles: STAFF,
    route: "/school/assessments",
    navHref: "/school/assessments",
    steps: [
      {
        target: "page-header",
        roles: ["TEACHER"],
        title: "Score entry",
        body: "Choose a classroom and subject, then enter each student's scores, or ratings for early-years classes. Press Save when you're done. A bar at the bottom shows how many changes are still unsaved.",
      },
      {
        title: "Remarks and traits",
        roles: ["TEACHER"],
        body: "Class teachers also write each student's termly remark here and rate behavioural traits, if your school uses them.",
      },
      {
        target: "page-header",
        roles: ADMINS,
        title: "Results and publishing",
        body: "Review a classroom's broadsheet and write head of level remarks. Publish results when they're ready. Guardians can only see a term's result after you publish it.",
      },
    ],
  },
  {
    key: "school.attendance",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Attendance",
    description: "Take the daily register for your class.",
    area: "Teaching",
    roles: STAFF,
    route: "/school/attendance",
    navHref: "/school/attendance",
    steps: [
      {
        target: "page-header",
        roles: ["TEACHER"],
        title: "The daily register",
        body: "Mark each student present or absent for the day. Guardians see their child's attendance in their own portal.",
      },
      {
        target: "page-header",
        roles: ADMINS,
        title: "Attendance overview",
        body: "See attendance recorded across your classrooms by their class teachers.",
      },
    ],
  },
  {
    key: "school.reports",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Result reports",
    description: "Preview, download and email printed result reports.",
    area: "Teaching",
    roles: STAFF,
    route: "/school/reports",
    navHref: "/school/reports",
    steps: [
      {
        target: "page-header",
        title: "Printed reports",
        body: "Preview any student's report card, download it as a PDF, or export a whole classroom's reports as one ZIP file.",
      },
    ],
  },
  {
    key: "school.report-settings",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Report settings",
    description: "Brand your report cards and choose who signs the head's remark.",
    area: "Setting up your school",
    roles: ADMINS,
    route: "/school/reports/settings",
    navHref: "/school/reports/settings",
    steps: [
      {
        target: "page-header",
        title: "Your report card",
        body: "Pick a template for each class and add your principal's name and signature. You can also show a class average column.",
      },
      {
        target: "page-tabs",
        title: "Remark commenters",
        body: "No principal? Set a Head of Nursery, Primary or Secondary to sign each class's head remark instead.",
      },
    ],
  },
  {
    key: "school.messages",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Messages",
    description: "Keep a running conversation with guardians about their child.",
    area: "Teaching",
    roles: STAFF,
    route: "/school/messages",
    navHref: "/school/messages",
    steps: [
      {
        target: "page-header",
        roles: ["TEACHER"],
        title: "Talk to guardians",
        body: "Log a note about a student, or send the same note to several or all of your class at once. Guardians can read and reply in their portal.",
      },
      {
        target: "page-header",
        roles: ADMINS,
        title: "Communication overview",
        body: "See the conversations your teachers are having with guardians.",
      },
    ],
  },
  {
    key: "school.lesson-notes",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Lesson notes",
    description: "Write weekly lesson notes and send them for review.",
    area: "Teaching",
    roles: STAFF,
    route: "/school/lesson-notes",
    navHref: "/school/lesson-notes",
    steps: [
      {
        target: "page-header",
        roles: ["TEACHER"],
        title: "Weekly lesson notes",
        body: "Pick a subject and week to write its note. Use the structured form or paste a Word document, then submit it for approval.",
      },
      {
        target: "page-header",
        roles: ADMINS,
        title: "Review lesson notes",
        body: "Approve submitted notes, or send them back with a comment.",
      },
    ],
  },
  {
    key: "school.take-home-quizzes",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Take-home quizzes",
    description: "Set quizzes students complete at home, scored automatically.",
    area: "Teaching",
    roles: STAFF,
    route: "/school/take-home-quizzes",
    navHref: "/school/take-home-quizzes",
    steps: [
      {
        target: "page-header",
        title: "Quizzes that mark themselves",
        body: "Write questions, set a deadline and publish. Students with a portal login take the quiz there. Everyone else gets a private link.",
      },
      {
        target: "page-actions",
        title: "Create a quiz",
        body: "Start a new quiz for one of your classrooms and subjects.",
      },
    ],
  },
  {
    key: "school.learning-resources",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Learning resources",
    description: "Share PDFs, notes, audio, video and YouTube videos with your students.",
    area: "Teaching",
    roles: STAFF,
    route: "/school/learning-resources",
    navHref: "/school/learning-resources",
    steps: [
      {
        target: "page-header",
        title: "Learning resources",
        body: "Choose a classroom and subject, then add resources your students can open from their portal. Publish a resource when it's ready.",
      },
    ],
  },
  {
    key: "school.billing",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Fees & bills",
    description: "Set up fees and prices, publish termly bills and confirm payments.",
    area: "Administration",
    roles: ADMINS,
    route: "/school/billing",
    navHref: "/school/billing",
    steps: [
      {
        target: "page-header",
        title: "Billing in three steps",
        body: "First define your fees. Next price them per class for the session. Then publish a term's bills, and guardians are emailed theirs.",
      },
      {
        target: "page-tabs",
        title: "Everything in tabs",
        body: "Bills, payments to confirm, fees, prices, school bus and settings each have their own tab.",
      },
    ],
  },
  {
    key: "school.inventory",
    version: 1,
    portal: "school",
    kind: "page",
    title: "Inventory",
    description: "Track stock, issue items and raise purchase requests.",
    area: "Administration",
    roles: ["SCHOOL_ADMIN", "BRANCH_ADMIN", "INVENTORY_MANAGER"],
    route: "/school/inventory",
    navHref: "/school/inventory",
    steps: [
      {
        target: "page-header",
        title: "Your school store",
        body: "Stock is tracked per branch. Every receipt, issue and adjustment is recorded, so the balance always adds up.",
      },
      {
        target: "page-tabs",
        title: "Requisitions and stock",
        body: "Raise a purchase request under Requisitions. Under Stock, issue items to a student or for general use.",
      },
    ],
  },
];
